name: Gradle CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
    paths:
      - 'app-*/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1.0.3    
      - name: Display Environment Variables
        run: env

  build_app_java:
    name: Java Application
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: Build Artifacts
        run: ./gradlew :app-java:build
      - name: Execute Main Class
        run: ./gradlew :app-java:run

  build_app_scala:
    name: Scala Application
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: Build Artifacts
        run: ./gradlew :app-scala:build
      - name: Execute Main Class
        run: ./gradlew :app-scala:run
